package com.jboss.soap.service.acmedemo;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-11-05T10:51:47.239Z
 * Generated source version: 2.7.10
 *
 */
@WebService(targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", name = "AcmeDemoInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface AcmeDemoInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listAvailablePlanes", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.ListAvailablePlanes")
    @WebMethod(action = "http://service.soap.jboss.com/AcmeDemo/listAvailablePlanes")
    @ResponseWrapper(localName = "listAvailablePlanesResponse", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.ListAvailablePlanesResponse")
    public Flight listAvailablePlanes(
                                      @WebParam(name = "in", targetNamespace = "") FlightRequest in);

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "bookFlights", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.BookFlights")
    @WebMethod
    @ResponseWrapper(localName = "bookFlightsResponse", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.BookFlightsResponse")
    public String bookFlights(
                              @WebParam(name = "in", targetNamespace = "") String in);

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "cancelBooking", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.CancelBooking")
    @WebMethod
    @ResponseWrapper(localName = "cancelBookingResponse", targetNamespace = "http://service.soap.jboss.com/AcmeDemo/", className = "com.jboss.soap.service.acmedemo.CancelBookingResponse")
    public int cancelBooking(
                             @WebParam(name = "in", targetNamespace = "") String in);
}
